# Generated by Django 6.1.1 on 2026-09-21 18:58

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('age_rating', models.PositiveSmallIntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')])),
                ('release_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('director', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('genres', models.ManyToManyField(related_name='films', to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveSmallIntegerField()),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('hall', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='main.hall')),
            ],
            options={
                'ordering': ['row_number', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('cancelled', 'Отменён'), ('finished', 'Завершён')], db_default='scheduled', default='scheduled', max_length=20)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='main.film')),
                ('hall', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='main.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main.customer')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='main.seat')),
                ('session', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='main.session')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='main.ticketstatus')),
            ],
        ),
        migrations.AddConstraint(
            model_name='film',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='films_duration_minutes_positive'),
        ),
        migrations.AddConstraint(
            model_name='film',
            constraint=models.CheckConstraint(condition=models.Q(('age_rating__in', [0, 6, 12, 16, 18])), name='films_age_rating_valid'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('hall', 'row_number', 'seat_number'), name='seats_hall_row_seat_uniq'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gt', 0)), name='seats_row_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.CheckConstraint(condition=models.Q(('seat_number__gt', 0)), name='seats_seat_number_positive'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['hall', 'start_time'], name='ix_sessions_hall_start_time'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='sessions_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('session', 'seat'), name='tickets_session_seat_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='tickets_price_non_negative'),
        ),
    ]
