# Generated by Django 6.1.1 on 2026-09-21 19:12

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='film',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False),
        ),
        migrations.AddField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False),
        ),
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
